version: '3'

env:
  DOTNET_ROOT: /home/vscode/.dotnet
  PATH:
    sh: echo "/home/vscode/.dotnet:$PATH"

includes:
  front:
    taskfile: ./front/Taskfile.yml
    dir: ./front
  back:
    taskfile: ./webapi/Taskfile.yml
    dir: ./webapi

tasks:
  default:
    desc: フロントとバックエンドを同時に起動する
    deps:
      - front:dev
      - back:dev
